### ISSUE TITLE
New template: migration

### ISSUE THREAD

**Issue by ThomasBinsfeld** [acsone/bobtemplates.odoo#36]
What about a new `migration` template that would generate migration script for a given module?
When being in the current module's directory: `mrbob bobtemplates.odoo:migration`

**It would ask for:**
 * new module version
 * use `openupgrade`? _(yes/no)_
 * pre-migrate? _(yes/no)_
 * post-migrate? _(yes/no)_

**And then it would:**
 * generate the `migrations/{version_number}/(pre/post)-migrate.py` file(s)
 * import `logging` and add a default `_logger.info()` message in the `migrate` method
 * if the use of `openupgrade` is selected:
   - import `openupgrade`
   - add the `@openupgrade.migrate(use_env=True)` decorator and use the `env` variable in the `migrate` method
   - add `openupgradelib` to the external dependencies of the manifest
 * change the version of the module accordingly

--------------------------------------
If it's relevant, the same could be done for pre/post-init hooks (I can write a separate issue for that).

**Comment by sbidoul** [comment]
+1, good idea

**Comment by MessiazMonteiro** [comment]
Hi Guys.. I´m using odoo 14.. and found out this error. can you help? Please.


(venv) C:\Users\Messias\PycharmProjects\Odoo14exe_nmodules>mrbob bobtemplates.odoo:addon
Traceback (most recent call last):
  File "C:\Users\Messias\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Messias\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Messias\PycharmProjects\Odoo14exe_nmodules\venv\Scripts\mrbob.exe\__main__.py", line 4, in <module>
  File "c:\users\messias\pycharmprojects\odoo14exe_nmodules\venv\lib\site-packages\mrbob\cli.py", line 11, in <module>
    from .configurator import Configurator
  File "c:\users\messias\pycharmprojects\odoo14exe_nmodules\venv\lib\site-packages\mrbob\configurator.py", line 6, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by sbidoul** [comment]
`readline` is part of the python stdlib. So if import readline fails, there must be a problem with your python installation. I'm marking these two comments as off-topic as they are irrelevant to the current issue. Please open another issue if you think there is a bug.
